const displayNameMap: Record<string, string> = {
  'Set De Regalos': 'Set de Regalos',
  'Bolígrafos-lápices-estuches': 'Bolígrafos, Lápices y Estuches',
  'Libretas-cuadernos-memo Set': 'Libretas, Cuadernos y Memo Set',
  'Tecnológicos': 'Tecnológicos',
  'Accesorios-herramientas': 'Accesorios y Herramientas',
  'Bolsas Publicitarias': 'Bolsas Publicitarias',
  'Mochilas-bananos-bolsos-morrales': 'Mochilas, Bolsos y Morrales',
  'Botellas-mugs-tazones-termos-vasos': 'Botellas, Mugs, Termos y Vasos',
  'Lanyards E Identificación': 'Lanyards e Identificación',
  'Línea Bamboo': 'Línea Bamboo',
  'Llaveros': 'Llaveros',
  'Novedades Publicitarios': 'Novedades',
  'Set De Vino-descorchadores-bolsas Para Vinos': 'Set de Vino y Descorchadores',
  'Set Parrillero-destapadores-posavasos': 'Set Parrillero y Destapadores',
  'Sacos De Yute': 'Sacos de Yute',
  'Trofeos Y Premios': 'Trofeos y Premios',
  'Belleza Y Salud': 'Belleza y Salud',
  'Packaging': 'Packaging',
  'Galvanos De Cristal': 'Galvanos de Cristal',
  'Galvanos De Madera Y Varios': 'Galvanos de Madera',
  'Copas 2024-2025': 'Copas 2024-2025',
  'Copas Línea Clásica': 'Copas Línea Clásica',
  'Copas Línea Comercial': 'Copas Línea Comercial',
  'Copas Y Torres': 'Copas y Torres',
  'Línea Cobre': 'Línea Cobre',
  'Medallas': 'Medallas',
  'Placas': 'Placas',
  'Trofeos': 'Trofeos',
  'Novedades Trofeos Y Premios': 'Novedades Trofeos y Premios',
  'Trofeos Plásticos': 'Trofeos Plásticos',
  'Trofeos Resina': 'Trofeos Resina',
  'Trofeos Acrílicos': 'Trofeos Acrílicos',
  'Trofeos Metálicos': 'Trofeos Metálicos',
  'Mugs Y Tazones': 'Mugs y Tazones',
  'Accesorios Automóvil': 'Accesorios Automóvil',
  'Accesorios Para Medallas': 'Accesorios para Medallas',
  'Accesorios Para Timbres': 'Accesorios para Timbres',
  'Audífonos-Parlantes': 'Audífonos y Parlantes',
  'Bandejas-Rocas': 'Bandejas y Rocas',
  'Cajas-estuches De Presentación': 'Cajas y Estuches de Presentación',
  'Cajas de Cartón Autoarmables': 'Cajas de Cartón Autoarmables',
  'Chapitas Publicitarias': 'Chapitas Publicitarias',
  'Cintas 1 Color': 'Cintas 1 Color',
  'Cintas 2 Colores': 'Cintas 2 Colores',
  'Cintas 3 Colores': 'Cintas 3 Colores',
  'Entretención y Outdoor': 'Entretención y Outdoor',
  'Envases Y Atomizadores': 'Envases y Atomizadores',
  'Equipos de Fútbol': 'Equipos de Fútbol',
  'Insumos': 'Insumos',
  'Kit De Copas': 'Kit de Copas',
  'Moldes Plástico': 'Moldes Plástico',
  'Moldes Resina': 'Moldes Resina',
  'Otros Tecnológicos': 'Otros Tecnológicos',
  'Pendrives': 'Pendrives',
  'Power Banks': 'Power Banks',
  'Recipientes De Vidrio': 'Recipientes de Vidrio',
  'Regalos y Trofeos Premium': 'Regalos y Trofeos Premium',
  'Sellos': 'Sellos',
  'Termos': 'Termos',
  'Torres': 'Torres',
  'Botellas': 'Botellas',
  'Bolsas Papel Kraft': 'Bolsas Papel Kraft',
  'Barrera Protección Acrílico': 'Barrera Protección Acrílico',
  'Timbres Automáticos': 'Timbres Automáticos',
  'Timbres Rectangulares Y Fechadores': 'Timbres Rectangulares y Fechadores',
  'Timbres Cuadrados Y Redondos': 'Timbres Cuadrados y Redondos',
  'Timbres De Bolsillo Y Dactilares': 'Timbres de Bolsillo y Dactilares',
};

export function getCategoryDisplayName(name: string): string {
  return displayNameMap[name] || name.replace(/-/g, ' ');
}
